### ISSUE TITLE
macos: add macos support

### ISSUE THREAD

**Issue by iwanbk** [threefoldtech/myceliumflut#58]
- [x] embed mycelium as static library #62
- [x] Make it on testflight #62
- [x] github actions build #65 
- [x] modify mycelium https://github.com/threefoldtech/mycelium/issues/428
