### ISSUE TITLE
add windows support

### ISSUE THREAD

**Issue by iwanbk** [threefoldtech/myceliumflut#59]
- [x] add windows support by calling mycelium as dynamic library #72
- [x] create the installer #84 
- [x] github actions build #75
- [x] add dev & usage docs #79
-  ~~github actions installer~~

**Comment by iwanbk** [comment]
all of the task has been completed
